import { readFile, writeFile, access } from 'node:fs/promises';
import { stringify } from 'yaml';

/** AIDF file paths for context injection. */
export interface AidfContext {
  rolePath?: string;
  taskPath?: string;
  planPath?: string;
  agentsPath?: string;
}

/** Context assembled from workspace metadata for AI CLI injection. */
export interface LaunchContext {
  workspacePath: string;
  workspaceName: string;
  gitIdentity?: { name: string; email: string };
  branch?: string;
  aidf?: AidfContext;
}

async function safeReadFile(path: string): Promise<string | undefined> {
  try { return await readFile(path, 'utf-8'); }
  catch { return undefined; }
}

async function fileExists(path: string): Promise<boolean> {
  try { await access(path); return true; }
  catch { return false; }
}

/**
 * Build a context string from workspace metadata and AIDF files.
 *
 * @param ctx - Launch context
 * @returns Markdown-formatted context string
 */
export async function buildContextString(ctx: LaunchContext): Promise<string> {
  const sections: string[] = [
    '## Workspace', '', `- **Name**: ${ctx.workspaceName}`, `- **Path**: ${ctx.workspacePath}`,
  ];
  if (ctx.gitIdentity) {
    sections.push('', '## Git Identity', '', `- **Name**: ${ctx.gitIdentity.name}`, `- **Email**: ${ctx.gitIdentity.email}`);
  }
  if (ctx.branch) sections.push('', '## Branch', '', `- **Current**: ${ctx.branch}`);
  if (ctx.aidf) {
    for (const [label, path] of [['Agents', ctx.aidf.agentsPath], ['Role', ctx.aidf.rolePath], ['Task', ctx.aidf.taskPath], ['Plan', ctx.aidf.planPath]] as const) {
      if (path) {
        const content = await safeReadFile(path);
        if (content) sections.push('', `## ${label}`, '', content.trim());
      }
    }
  }
  return sections.join('\n');
}

/**
 * Generate a temporary CLAUDE.md file with context.
 *
 * @param ctx - Launch context
 * @param outputPath - Path for the generated file
 * @returns The output path
 */
export async function generateClaudeMd(ctx: LaunchContext, outputPath: string): Promise<string> {
  const content = await buildContextString(ctx);
  await writeFile(outputPath, `# DitLoop Context\n\n> Auto-generated by DitLoop.\n\n${content}\n`, 'utf-8');
  return outputPath;
}

/**
 * Generate an .aider.conf.yml with context for Aider.
 *
 * @param ctx - Launch context
 * @param outputPath - Path for the generated file
 * @returns The output path
 */
export async function generateAiderConf(ctx: LaunchContext, outputPath: string): Promise<string> {
  const readFiles: string[] = [];
  if (ctx.aidf) {
    for (const p of [ctx.aidf.agentsPath, ctx.aidf.rolePath, ctx.aidf.taskPath, ctx.aidf.planPath]) {
      if (p && await fileExists(p)) readFiles.push(p);
    }
  }
  const config: Record<string, unknown> = {};
  if (readFiles.length > 0) config['read'] = readFiles;
  config['message'] = `Workspace: ${ctx.workspaceName} (${ctx.workspacePath})`;
  await writeFile(outputPath, stringify(config), 'utf-8');
  return outputPath;
}
